using System;

namespace PyTaskAvalonia.Services;

internal static class InputSignature
{
    // Reuse a stable marker to tag synthetic input generated by the app.
    public static readonly IntPtr Value = new(unchecked((int)0x5A17B10C));
    public static readonly UIntPtr UIntValue = (UIntPtr)(ulong)(long)Value;
}

